rsync -rv /Users/mturja/PycharmProjects/DeepGraphKoopmanOperator/dataloaders mturja@janus.ia.unc.edu:/export_home/mturja/DeepGraphKoopmanOperator/
rsync -rv /Users/mturja/PycharmProjects/DeepGraphKoopmanOperator/experiments mturja@janus.ia.unc.edu:/export_home/mturja/DeepGraphKoopmanOperator/
rsync -rv /Users/mturja/PycharmProjects/DeepGraphKoopmanOperator/layers mturja@janus.ia.unc.edu:/export_home/mturja/DeepGraphKoopmanOperator/
rsync -rv /Users/mturja/PycharmProjects/DeepGraphKoopmanOperator/models mturja@janus.ia.unc.edu:/export_home/mturja/DeepGraphKoopmanOperator/
rsync -rv /Users/mturja/PycharmProjects/DeepGraphKoopmanOperator/trainers mturja@janus.ia.unc.edu:/export_home/mturja/DeepGraphKoopmanOperator/
rsync -rv /Users/mturja/PycharmProjects/DeepGraphKoopmanOperator/utils mturja@janus.ia.unc.edu:/export_home/mturja/DeepGraphKoopmanOperator/
rsync -rv /Users/mturja/PycharmProjects/DeepGraphKoopmanOperator/CONSTANTS.py mturja@janus.ia.unc.edu:/export_home/mturja/DeepGraphKoopmanOperator/
rsync -rv /Users/mturja/PycharmProjects/DeepGraphKoopmanOperator/post_processing mturja@janus.ia.unc.edu:/export_home/mturja/DeepGraphKoopmanOperator/
rsync -rv /Users/mturja/PycharmProjects/DeepGraphKoopmanOperator/*sh mturja@janus.ia.unc.edu:/export_home/mturja/DeepGraphKoopmanOperator/
rsync -rv /Users/mturja/PycharmProjects/DeepGraphKoopmanOperator/baselines mturja@janus.ia.unc.edu:/export_home/mturja/DeepGraphKoopmanOperator/
#rsync -rv /Users/mturja/PycharmProjects/DeepGraphKoopmanOperator/data/M4 mturja@janus.ia.unc.edu:/export_home/mturja/DeepGraphKoopmanOperator/data/